### PR TITLE
Update/add pinum callback to methods

### PR DESCRIPTION
**Pull request by edgarsilva**

### CODE REVIEW

**Comment by edgarsilva** [comment]
Everyting passes, but build fails because travis does not support the I2C libraries. I'm gonna check if I can manually install the i2c libraries. This addresses issue #29.

**Comment by stewart** [comment]
Unsure about this, since we currently really want to support Node v0.10.XX since that's what normally comes on all these single-board computers, and updating can be painful. @deadprogram + @zankich, any thoughts?

**Comment by deadprogram** [comment]
I agree with @stewart we really need to still support node 0.10.x versions

**Comment by edgarsilva** [comment]
I'll put it back in, after testing libraries locally since it seems latest version of I2C does not compile in travis on node 10. If it comes to it I will lock it on an older version of I2C module.

**Comment by stewart** [comment]
:computer:

**Pull request merged**
